-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
-- For the "Semantic Brain" (Feature #2)
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. USERS (Standard Auth)
CREATE TABLE users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    storage_quota_bytes BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. FILES (The Core Entity)
CREATE TABLE files (
    file_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(user_id),
    
    -- Basic Metadata
    file_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL, -- Physical location on disk/S3
    mime_type VARCHAR(100),
    size_bytes BIGINT,
    
    -- "Duplicate Detective" (Feature #6)
    -- We store a hash to instantly find exact duplicates
    content_hash VARCHAR(64), 
    
    -- "Smart Purge" & Cache Flagging
    -- 'active': Normal file
    -- 'archived': User moved to deep storage
    -- 'rot': System detected junk (Cache, AppData, Temp)
    lifecycle_status VARCHAR(20) DEFAULT 'active' CHECK (lifecycle_status IN ('active', 'archived', 'rot', 'trash')),
    
    -- "Zen Sort" (Feature #1)
    -- The AI's confidence score (0-100) that this file is in the right folder.
    -- If low, we suggest moving it.
    organization_score INT DEFAULT 0,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_accessed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. FILE_VERSIONS ("Time Travel" - Feature #7)
-- Stores previous states of a file for the visual timeline scrubber
CREATE TABLE file_versions (
    version_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    file_id UUID REFERENCES files(file_id) ON DELETE CASCADE,
    file_path_snapshot TEXT NOT NULL, -- Where this specific version is stored
    change_summary TEXT, -- e.g., "Updated budget numbers"
    modified_by UUID REFERENCES users(user_id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. AI_METADATA ("The Brain")
-- This table powers the "Conversation Search" and "Shapeshifter Previews"
CREATE TABLE ai_metadata (
    file_id UUID REFERENCES files(file_id) ON DELETE CASCADE PRIMARY KEY,
    
    -- "Semantic Memory" (Feature #2)
    -- A vector embedding of the file's content for natural language search.
    -- 1536 is standard for OpenAI Ada-002 models.
    content_vector vector(1536),
    
    -- "Shapeshifter" (Feature #5)
    -- A 3-bullet summary generated by AI for the hover preview.
    summary_text TEXT,
    
    -- "Privacy Redactor" (Feature #4)
    -- Flags if the file contains PII (SSN, Credit Cards, etc.)
    contains_pii BOOLEAN DEFAULT FALSE,
    pii_types JSONB, -- e.g. ["ssn", "phone_number"]
    
    -- "Auto-Tagging"
    -- Flexible tags like ["Invoice", "Project Alpha", "Urgent"]
    auto_tags JSONB 
);

-- 5. CONTEXT_CLUSTERS ("Meeting Mapper" & "Project DNA" - Features #3 & #8)
-- Dynamic folders that don't exist on disk, but exist in the App logic.
CREATE TABLE context_clusters (
    cluster_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(user_id),
    
    -- e.g., "Meeting: Budget Review" or "Project Alpha"
    name VARCHAR(255),
    
    -- 'event': Created from a calendar event
    -- 'project': Created from folder analysis
    -- 'desktop_pile': Created for the Desktop Piles feature
    cluster_type VARCHAR(50),
    
    -- The criteria used to group these files dynamically
    -- e.g. { "keywords": ["budget", "finance"], "date_range": "2025-10-01..." }
    grouping_logic JSONB,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
