import { promises as fs } from 'fs'
import path from 'path'
import { aiService } from './ai-service'
import { logger } from './logger'

class DnaService {
  private static instance: DnaService

  private constructor() {}

  static getInstance(): DnaService {
    if (!DnaService.instance) {
      DnaService.instance = new DnaService()
    }
    return DnaService.instance
  }

  async generateProjectDna(folderPath: string): Promise<string> {
    try {
      logger.info(`Generating DNA for ${folderPath}`)
      
      // 1. Scan folder for significant files to summarize
      const files = await fs.readdir(folderPath)
      const meaningfulFiles = files.filter(f => !f.startsWith('.') && !f.startsWith('node_modules') && f !== 'README.md')
      
      let context = ""
      const MAX_CONTEXT = 10000 // characters

      for (const file of meaningfulFiles) {
          const filePath = path.join(folderPath, file)
          const stats = await fs.stat(filePath)
          
          if (stats.isDirectory()) continue

          // Check extension
          const ext = path.extname(file).toLowerCase()
          if (['.txt', '.md', '.ts', '.tsx', '.js', '.jsx', '.json', '.py', '.java', '.c', '.cpp', '.h', '.css', '.html'].includes(ext)) {
               const content = await fs.readFile(filePath, 'utf-8')
               // Add snippet
               context += `\n--- FILE: ${file} ---\n${content.substring(0, 500)}\n`
               if (context.length > MAX_CONTEXT) break
          }
      }

      if (context.length < 50) {
          return "Insufficient content to generate DNA."
      }

      // 2. Generate Summary
      const prompt = `Summarize this project based on the following file snippets. Generate a brief README.md introduction:\n${context}`
      const summary = await aiService.generateSummary(prompt)

      // 3. Write README.md
      const readmePath = path.join(folderPath, 'README.md')
      const readmeContent = `# Project DNA\n\n> Auto-generated by FileZen\n\n## Summary\n${summary}\n\n## Structure\n- ${meaningfulFiles.slice(0, 10).join('\n- ')}${meaningfulFiles.length > 10 ? '\n- ...' : ''}`
      
      await fs.writeFile(readmePath, readmeContent)
      
      return readmeContent
      
    } catch (error: any) {
      logger.error("Failed to generate Project DNA", { error: error.message })
      throw error
    }
  }
}

export const dnaService = DnaService.getInstance()
